# Generated by Django 2.2.6 on 2019-11-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='actross_cities',
            new_name='across_cities',
        ),
    ]
